#!/bin/bash
# Tag and push a release.

set -e

# Make sure the darn thing works

npm update && npm run test

# Make sure we're on the master branch.

(git branch | grep -q '* master') || {
  echo "Only release from the master branch."
  exit 1
}

# Make sure there isn't anything uncommitted.

test -z "$(git status -s)" || {
  echo "You have uncommitted changes! Commit them first."
  exit 1
}

# Figure out what version we're releasing.

tag=v`node -e 'console.log(require("./package.json").version)'`

# Make sure we haven't released this version before.

git fetch -t origin

(git tag -l | grep -q "$tag") && {
  echo "Whoops, there's already a '${tag}' tag."
  exit 1
}

# Tag it and bag it.

git tag "$tag" &&
  git push origin master &&
  git push origin "$tag"

open https://github.com/vsco/dcdr-js/releases/tag/$tag || {
  echo "Go and add release notes here, please!"
  echo ""
  echo "https://github.com/vsco/dcdr-js/releases/tag/$tag"
}
